### ISSUE TITLE
2.0.5 git tag and artifact mismatch

### ISSUE THREAD

**Issue by zsedem** [doriordan/skuber#128]
I think there were some errors during the release of 2.0.5
After downloading from [central-maven](http://central.maven.org/maven2/io/skuber/skuber_2.12/2.0.5/skuber_2.12-2.0.5.jar)
The jar does not contain the /skuber/Pod$Toleration* classes, which is available in the git tag v2.0.5

**Comment by doriordan** [comment]
Reviewing the release I think the 2.0.5 tag should have been applied to the HEAD at:
https://github.com/doriordan/skuber/commit/0f576b58d67ed8e6275583ffa48d4077166504c7
instead of: 
https://github.com/doriordan/skuber/commit/615c964da18390822dfefb74a10cd2b5d32d4d81

So basically the release on Maven is missing the PodToleration changes from PR#122 plus some test enhancements relative to the tagged version.

Not sure how that happened, but releasing to Sonatype (sbt task) and tagging the release (using git) are separate manual steps so I must have inadvertently performed them on different commits.

I have now fixed the tag so it reflects the actual release.

Apologies for any inconvenience. How urgently do you need a release with the PodToleration changes? I plan to release point versions quite regularly.

**Comment by zsedem** [comment]
Not too urgent now, i just want to remove our internal fork, which now only contains this change
