### ISSUE TITLE
Play 2.5 support

### ISSUE THREAD

**Issue by kbalyasnikov** [doriordan/skuber#15]
Hi!

Are there any plans to support play 2.5? skuber 1.3 is not compatible with it.

**Comment by doriordan** [comment]
Hi

No immediate plans (but PR always welcome ...)

I would be interested to know what issues you are having with Skuber/Play 2.5. I know iteratees/enumeratees is deprecated and have been superseded by Akka streams so the watch functionality will need updating.

**Comment by geula** [comment]
Hi, 
I encountered a problem with Play 2.5 also, the error message was :

**Comment by etsrepo** [comment]
any progress?

**Comment by doriordan** [comment]
This is linked to issue #56 as the Scala 2.12 and the Play version upgrades are very likely to be done together. At the moment you may be able to use the work already done for  #54, hopefully we can complete that work fairly soon but can't give a date right now.

**Comment by doriordan** [comment]
I'm going to close this as the release_2.0 branch has moved to using latest Akka HTTP client instead of Play WS (see comment in #56) - this means it should not interfere with applications use of Play 2.5/2.6 so should resolve the above issues. I can reopen if there are still issues with using later versions of Play with release_2.0.
