### ISSUE TITLE
How to get a PodList from all namespaces?

### ISSUE THREAD

**Issue by dmitriyvolk** [doriordan/skuber#20]
Hi! I have a hard time trying to list all pods from all namespaces in my cluster.

**Comment by doriordan** [comment]
Hi! Currently I think this would be quite difficult to do, because the key abstraction through which the client API works (the request context returned by k8sInit) is specific to one namespace.
It is an interesting use case though, and I think it would be useful to support a kind of '--all-namespaces' switch or mode for list requests. I'll have to think about how best to support this though.

**Comment by dmitriyvolk** [comment]
From the API consumer point of view, I would probably like something like:
```
k8sContext.list[PodList] — will use namespace configured during init
k8sContext.inNamespace(Namespace.all).list[PodList]
k8sContext.inNamespace(Namespace.forName("my-custom-namespace").list[PodList]
```
An alternative would be to allow using `Namespace.all` in the initial config — currently if I set `Namespace.all` in the `Configuration`, it makes the client use `default` namespace.

**Comment by doriordan** [comment]
I've merged an enhancement to support this and related requirements:
https://github.com/doriordan/skuber/pull/21
See the new list example for details, and the updated programming guide.
So closing this for now, let me know if it works for you.
