### ISSUE TITLE
Copy functionality for ObjectResource

### ISSUE THREAD

**Issue by soujiro32167** [doriordan/skuber#252]
It would be nice to be able to copy arbitrary `ObjectResource`s, since all of its implementations are case classes. I am struggling to update (copy) in this scenario, based on one of your tests:
```
def upsert[T <: ObjectResource](obj: T)(implicit fmt: Format[T],rd: ResourceDefinition[T]): Future[T] = {

    k8s create obj recoverWith {
      case alreadyExists: K8SException if alreadyExists.status.code.contains(409) =>
        // update needs to use the current resource version of existing resource in order to be accepted by k8s
        k8s get obj.name flatMap { existing =>
          val currentVersion = existing.metadata.resourceVersion
          // copy constructor

          // returns an ObjectReference instead of ObjectResource
          k8s update obj.copy(resourceVersion = currentVersion)
        }
    }
  }
```

**Comment by doriordan** [comment]
Hi @soujiro32167 - because `ObjectResource` is itself not a concrete case class, it does not support `copy`.
@amir and I looked at similar challenges in other scenarios, and we came up with an approach used by @amir in the `cr4s` project - the approach uses Shapeless to make modifications to generic fields of object resources - see https://github.com/amir/cr4s/blob/master/core/src/main/scala/GenericResourceModifiers.scala, which enables metadata to be set on any object resource. A similar approach should be possible for your use case if I understand it correctly (update resource version of generic object resource)

**Comment by soujiro32167** [comment]
Thanks for the reply, @doriordan. I'm having a hard time following since I'm new to Scala, but will try the approach

**Comment by pawelprazak** [comment]
Yes, metadata modification comes up very often. Not sure throwing shapless at it is the best solution. On the other hand I don't have a better solution ATM. Anyway just wanted to not that this issue is still open IMO.

**Comment by pawelprazak** [comment]
Wouldn't the same approach as `CustomResource` work?:
```def withMetadata(metadata: ObjectMeta) = this.copy(metadata = metadata)```
