### ISSUE TITLE
Cannot scale Deployment to zero instances

### ISSUE THREAD

**Issue by cgbaker** [doriordan/skuber#48]
When attempting to scale a deployment to zero instances, the `replicas` field is neglected from the JSON output, resulting in the deployment being scaled to (default) 1 instance. 
The reason is that the `Format[Deployment]` is configured to treat `replicas` as `formatMaybeInt()`, which uses zero as a indicator value for a missing argument.

I'm going to push a branch with a documenting test, but I'd appreciate some feedback from @doriordan (or anyone) as to the preferred approach to solve the issue (this specific issue with Deployment, and the issue in general). My inclination is to modify `formatMaybeInt` to use a different sentinel value (maybe -1? that feels like kicking the can down the road...)

**Comment by doriordan** [comment]
Just for background - the purpose of formatMaybeInt/String/..  etc.has been to deal with the many optional fields on the Kubernetes API that if omitted basically default to "zero" (which in common with Go translates to 0 in the case of integers). The alternative would have been to use Option types in the model for all these fields, but I felt it would have been an extra overhead on users of Skuber to wrap/unwrap them.
So...in this case I think it is just a bug (introduced by me probably...) that it is used to format the replicas field on Deployments, because that defaults to 1 rather than zero so isn't the intended use of formatMaybeInt.
I'd be concerned that changing the default / sentinel value for formatMaybeInt as per suggested fix could break existing apps at runtime.
One way to deal with this would be to make the replica field an Option type, since the default doesn't map to a "zero" value. That would mean a change to the current API but at least would be checked / enforced at compile time.
Otherwise we could parametrise formatMaybeInt with an integer value (defaulted to 0) which can be used to specify the default value for any particular field something like (not tested)
// Int: the empty value is 0 (unless overridden)
    def formatMaybeEmptyInt(omitEmpty: Boolean=true, defaultValue:Int = 0) : OFormat[Int] =
      path.formatNullable[Int].inmap[Int](_.getOrElse(defaultValue), i => if (omitEmpty && i==defaultValue) None else Some(i))

**Comment by cgbaker** [comment]
To be clear... the problem isn't that the output defaults to one, the problem is that if `replicas` is set to 0, Skuber excludes `replicas` from the output (and then the Kube server treats that as `1`). 
I'm a little worried about a solution where a present value would be nuked from the rendering because of a poorly chosen `defaultValue`. But in this case, maybe it's better to make the small change and switch `replicas` to `Option[Int]` like you suggested. I'll update my PR with that change.

**Comment by cgbaker** [comment]
I updated the branch for #49 to change `replicas` from `Int` to `Option[Int]`. As you noted above, this is a non-backwards-compatible change to the API. Only users that are directly creating a `DeploymentSpec` will run into this problem.

This branch doesn't make any changes to `formatMaybeEmptyInt`, so that there is still the following behavior (pseudo-code): 
```
formatMaybeEmptyInt().write(0) == JsNull
```
I've added a test to document this behavior: 
https://github.com/GalacticFog/skuber/blob/44db2238bd28f962a2ff7721074f404354f09cba/client/src/test/scala/skuber/json/FormatMaybeSpec.scala

I noticed that both `StatefulSet.Spec` and `ReplicaSet.Spec` both have a `replicas` field using `formatMaybeEmptyInt`, and I'm supposing that these are probably not scalable to 0 because of the same issue. What's your @doriordan opinion on addressing these? Same as here, with `Option[Int]`?

**Comment by doriordan** [comment]
It looks to me like where ever replicas are an optional field that defaults to non-zero, they generally should be Option[Int] types - good spot. Along with the kinds you mention I think scaler kinds (e.g.. HorizonatalPodAutoscaler) would need this change.

**Comment by cgbaker** [comment]
I added changes and test for `StatefulSet.Spec`, `ReplicaSet.Spec` and `HPAS.Spec`. I left `*.Status.replica_` alone, it seems like it should be fine. Those are the only usages of `formatMaybeEmptyInt` relating to replicas that I found.

**Comment by cgbaker** [comment]
i think this one is ready to merge, so I've removed WIP from #49 ; check it out, @doriordan , please let me know if there's anything you'd like added/changed in that PR.

**Comment by doriordan** [comment]
merged #49 thanks
